add docker compose file
pluginkollektiv/antispam-bee pull request #364
Opened 2020-11-04 08:05 UTC by pfefferle

to simplify local testing

> To test the plugin on your local machine, simply run `docker-compose up` in the root folder and open `http://localhost:8081/` in your browser.

2020-11-25 10:32 UTC, pfefferle commented
@2ndkauboy friendly ping ;)

2020-12-21 19:55 UTC, 2ndkauboy commented
Works perfectly even with WSL :)

2020-12-21 19:58 UTC, 2ndkauboy approved these changes

2020-12-21 20:00 UTC, pfefferle commented
Thanks @2ndkauboy

2020-12-21 20:00 UTC, merged

2020-12-21 20:02 UTC, 2ndkauboy requested changes

2020-12-21 20:02 UTC, 2ndkauboy commented on README.md
> +* To test the plugin on your local machine, simply run `docker-compose up` in the root folder and open `http://localhost:8081/` in your browser.
@pfefferle Maybe write that they should use `docker-compose up -d` to run it in "detached mode"?