Change link to ISO.org
pluginkollektiv/antispam-bee pull request #463
Opened 2022-07-28 09:00 UTC by stkjj

issue #462

2022-10-31 09:18 UTC, stklcode requested changes

2022-10-31 09:18 UTC, stklcode commented on inc/gui.class.php
> +											__( 'https://www.iso.org/obp/ui/#search', 'antispam-bee' ),
The proposed link leads to the empty search page when opened outside an existing session and is not really helpful in this case.

Guess the intention was https://www.iso.org/obp/ui/#search/code/
(also see https://github.com/pluginkollektiv/antispam-bee/issues/462#issuecomment-1296804571 for discussion)

2023-04-06 06:15 UTC, stklcode approved these changes

2023-04-13 09:52 UTC, florianbrinkmann approved these changes

2023-04-13 10:12 UTC, merged